export const MINI_MAIN_ROUTES = {
  home: '/pages/home/index',
  park: '/pages/park/index',
  member: '/pages/member/index',
} as const;

export const MINI_PACKAGE_ROUTES = {
  mallHome: '/pkg-mall/pages/index/index',
  memberHome: '/pkg-member/pages/index/index',
  memberCode: '/pkg-member/pages/member-code/index',
  hotelHome: '/pkg-hotel/pages/index/index',
  ticketHome: '/pkg-ticket/pages/index/index',
  ticketBooking: '/pkg-ticket/pages/ticket-booking/index',
  diningHome: '/pkg-dining/pages/index/index',
  orderHome: '/pkg-order/pages/index/index',
  mallCategory: '/pkg-mall/pages/category/index',
  mallCategoryList: '/pkg-mall/pages/category-list/index',
  mallSearch: '/pkg-mall/pages/search/index',
  mallProducts: '/pkg-mall/pages/products/index',
  mallRecommend: '/pkg-mall/pages/recommend/index',
  mallProductDetail: '/pkg-mall/pages/product-detail/index',
  mallCart: '/pkg-mall/pages/cart/index',
  mallFavorites: '/pkg-mall/pages/favorites/index',
  mallGiftSelect: '/pkg-mall/pages/gift-select/index',
  ticketParkDetail: '/pkg-ticket/pages/park-detail/index',
  ticketParkGuide: '/pkg-ticket/pages/park-guide/index',
  ticketCheckout: '/pkg-ticket/pages/checkout/index',
  hotelCheckout: '/pkg-hotel/pages/checkout/index',
  hotelRoomDetail: '/pkg-hotel/pages/room-detail/index',
  diningMerchantDetail: '/pkg-dining/pages/merchant-detail/index',
  diningCheckout: '/pkg-dining/pages/checkout/index',
  orderDetail: '/pkg-order/pages/detail/index',
  orderCheckout: '/pkg-order/pages/checkout/index',
  orderAddress: '/pkg-order/pages/address/index',
  orderAddressEdit: '/pkg-order/pages/address-edit/index',
  orderCancel: '/pkg-order/pages/cancel/index',
  orderAftersaleApply: '/pkg-order/pages/aftersale-apply/index',
  orderAftersaleType: '/pkg-order/pages/aftersale-type/index',
  orderAftersaleList: '/pkg-order/pages/aftersale-list/index',
  orderAftersaleProgress: '/pkg-order/pages/aftersale-progress/index',
  orderLogistics: '/pkg-order/pages/logistics/index',
  orderReviewCreate: '/pkg-order/pages/review-create/index',
  orderReviewList: '/pkg-order/pages/review-list/index',
  memberCoupons: '/pkg-member/pages/coupons/index',
  memberShareRule: '/pkg-member/pages/share-rule/index',
  memberShare: '/pkg-member/pages/share/index',
  memberShareIncome: '/pkg-member/pages/share-income/index',
  memberShareInvite: '/pkg-member/pages/share-invite/index',
  memberWithdrawRecords: '/pkg-member/pages/withdraw-records/index',
  memberWithdraw: '/pkg-member/pages/withdraw/index',
} as const;

export type MiniMainRoute = (typeof MINI_MAIN_ROUTES)[keyof typeof MINI_MAIN_ROUTES];
export type MiniPackageRoute = (typeof MINI_PACKAGE_ROUTES)[keyof typeof MINI_PACKAGE_ROUTES];
export type MiniRoute = MiniMainRoute | MiniPackageRoute;
